name=TinyDisplay
version=2.0.0
author=Stefan Trippler <stefan@trippler.de>
maintainer=Stefan Trippler <stefan@trippler.de>
sentence=Simple text-only library for OLED display SSD1306
paragraph=Very small footprint (no memory buffer for operation needed)
category=Display
url=https://github.com/steftri/TinyDisplay
architectures=*
license=CC BY
includes=TinyDisplay.h
